version: '3'

services:
  web:
    build: .
    command: daphne mywebsite.asgi:application --port 8000 --bind 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch 
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  celery:
    build: .
    command: celery -A mywebsite worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
