version: '3'

services:
  web:
    build: .
    command: daphne mywebsite.asgi:application --port 8000 --bind 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch  # Elasticsearch'e bağlılık ekle
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # Elasticsearch URL'si ortam değişkeni olarak ekle

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
